base_url = "https://www.cs.cornell.edu/courses/cs6120/2020fa"
compile_sass = true
build_search_index = false
generate_rss = true

highlight_code = true
highlight_theme = "inspired-github"

title = "CS 6120"

[extra]
favicon = "/img/favicon.ico"
bigicon = "/img/favicon152.png"

[[extra.links]]
name = "Zulip"
url = "https://cs6120.zulipchat.com"
